# 회원가입
PUT http://localhost:9988/api/member/join HTTP/1.1
content-type: application/json

{
    "email" : "user05@service.com",
    "pwd" : "1234",
    "name" : "사용자5",
    "birth" : "2022-12-14T00:00:00",
    "reg_dt" : "2022-12-14T00:00:00"
}

################################################
# 로그인
POST http://localhost:9988/api/member/login HTTP/1.1
content-type: application/json

{
    "email" : "user01@service.com",
    "pwd" : "1234"
}

################################################
# 일정추가
PUT http://localhost:9988/api/todo/add HTTP/1.1
content-type: application/json

{
    "content":"우하하하",
    "status":1,
    "startDt":"2022-12-19T00:30:00",
    "endDt":"2022-12-23T09:10:00"
}

################################################
# 리스트조회
GET http://localhost:9988/api/todo/list HTTP/1.1

################################################
# 수정
PATCH http://localhost:9988/api/todo/update/status?seq=1&value=1 HTTP/1.1

################################################

PATCH http://localhost:9988/api/todo/update/content?seq=1&value=여러분메리크리스마스에요~ HTTP/1.1

################################################

DELETE http://localhost:9988/api/todo/delete?seq=2 HTTP/1.1

################################################

GET http://localhost:9988/api/todo/list/term?start=20211220&end=20221230